import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
   "~/.config/alacritty/catppuccin-mocha.toml"
]

shell = "nu"

[window]
dimensions = { columns = 160, lines = 430}
startup_mode = "Windowed"
opacity = 0.9

[font]
normal = { family = "FiraCode NerdFont", style = "regular" }

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" }
]
