#theme = "rose_pine"
theme = "catppuccin_mocha"

[editor]
true-color = true
color-modes = true
bufferline = "multiple"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
